data_types = {
    "dynamo_customers_recon": {
        "date": "date",
        "status": "string",
        "count_dynamo": "int",
        "count_athena": "int",
        "timestamp": "timestamp",
    },
    "dynamo_card_fast_messages_recon": {
        "date": "date",
        "count_dynamo": "int",
        "count_athena": "int",
        "timestamp": "timestamp",
        "all_match": "boolean",
    },
    "dynamo_cards_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_onfido_recon": {
        "count_dynamo": "int",
        "count_athena": "int",
        "date": "date",
        "timestamp_extract": "timestamp",
    },
    "dynamo_mortgage_app_recon": {
        "count_dynamo": "int",
        "count_athena": "int",
        "date": "date",
        "timestamp_extract": "timestamp",
    },
    "dynamo_mortgage_in_principle": {
        "count_dynamo": "int",
        "count_athena": "int",
        "date": "date",
        "timestamp_extract": "timestamp",
    },
    "dynamo_customer_finances": {
        "count_dynamo": "int",
        "count_athena": "int",
        "date": "date",
        "timestamp_extract": "timestamp",
    },
    "dynamo_cardorders_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_riskscore_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_riskscorehist_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_customer_risk_crm_case_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_financing_mortgage_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_customer_passport_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_customer_risk_form_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_customer_identity_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_cards_status_history_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_customer_address_address_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_document_verification_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_confirmation_of_payee_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_payees_v2_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
    "dynamo_ias_recurring_recon": {
        "date": "date",
        "dynamo_state": "string",
        "dynamo_count": "int",
        "athena_state": "string",
        "athena_count": "int",
        "timestamp": "timestamp",
    },
}
